/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package frame;

import configDB.crud_wilayah; // Import kelas CRUD yang sesuai
import java.sql.Date; // Penting untuk konversi JDateChooser
import javax.swing.JOptionPane;

/**
 *
 * @author User
 */
public class frame_wilayah extends javax.swing.JFrame {

    private crud_wilayah objekKu; // Objek CRUD

    /**
     * Creates new form frame_wilayah
     */
    public frame_wilayah() {
        initComponents();
        this.setLocationRelativeTo(null);
        objekKu = new crud_wilayah(); // Inisialisasi objek
        txtIdWilayah.setEnabled(false); // ID Wilayah di-set oleh database (AI)
        segarkanTabel(); // Tampilkan data saat frame pertama kali dibuka
    }

    // Metode untuk menyegarkan data tabel
    private void segarkanTabel() {
        // Panggil metode tampil dari CRUD dengan SQL default
        objekKu.tampilDataWilayah(tableWilayah, "select * from wilayah");
    }

    // Metode untuk mengosongkan form
    private void kosongkanForm() {
        txtIdWilayah.setText(null);
        txtWilayahPenyimpanan.setText(null);
        datePenyimpanan.setDate(null); // Kosongkan JDateChooser
        datePemindahan.setDate(null); // Kosongkan JDateChooser
        dateRestok.setDate(null); // Kosongkan JDateChooser
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        txtIdWilayah = new javax.swing.JTextField();
        txtWilayahPenyimpanan = new javax.swing.JTextField();
        datePenyimpanan = new com.toedter.calendar.JDateChooser();
        datePemindahan = new com.toedter.calendar.JDateChooser();
        dateRestok = new com.toedter.calendar.JDateChooser();
        btnTambah = new javax.swing.JButton();
        btnUpdate = new javax.swing.JButton();
        btnHapus = new javax.swing.JButton();
        txtCari = new javax.swing.JTextField();
        jScrollPane1 = new javax.swing.JScrollPane();
        tableWilayah = new javax.swing.JTable();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);
        setTitle("Kelola Wilayah Penyimpanan");

        jLabel1.setText("ID Wilayah");

        jLabel2.setText("Wilayah Penyimpanan");

        jLabel3.setText("Tanggal Penyimpanan");

        jLabel4.setText("Tanggal Pemindahan");

        jLabel5.setText("Tanggal Restok");

        datePenyimpanan.setDateFormatString("yyyy-MM-dd");

        datePemindahan.setDateFormatString("yyyy-MM-dd");

        dateRestok.setDateFormatString("yyyy-MM-dd");

        btnTambah.setText("Tambah");
        btnTambah.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnTambahActionPerformed(evt);
            }
        });

        btnUpdate.setText("Update");
        btnUpdate.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnUpdateActionPerformed(evt);
            }
        });

        btnHapus.setText("Hapus");
        btnHapus.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnHapusActionPerformed(evt);
            }
        });

        txtCari.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyPressed(java.awt.event.KeyEvent evt) {
                txtCariKeyPressed(evt);
            }
        });

        tableWilayah.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null, null},
                {null, null, null, null, null},
                {null, null, null, null, null},
                {null, null, null, null, null}
            },
            new String [] {
                "Title 1", "Title 2", "Title 3", "Title 4", "Title 5"
            }
        ));
        tableWilayah.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                tableWilayahMouseClicked(evt);
            }
        });
        jScrollPane1.setViewportView(tableWilayah);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(30, 30, 30)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(jScrollPane1, javax.swing.GroupLayout.DEFAULT_SIZE, 468, Short.MAX_VALUE)
                    .addComponent(txtCari)
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel1)
                            .addComponent(jLabel2)
                            .addComponent(jLabel3)
                            .addComponent(jLabel4)
                            .addComponent(jLabel5))
                        .addGap(25, 25, 25)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(txtIdWilayah)
                            .addComponent(txtWilayahPenyimpanan)
                            .addComponent(datePenyimpanan, javax.swing.GroupLayout.DEFAULT_SIZE, 160, Short.MAX_VALUE)
                            .addComponent(datePemindahan, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(dateRestok, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                        .addGap(35, 35, 35)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(btnHapus, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(btnUpdate, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(btnTambah, javax.swing.GroupLayout.DEFAULT_SIZE, 130, Short.MAX_VALUE))))
                .addContainerGap(30, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(24, 24, 24)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel1)
                    .addComponent(txtIdWilayah, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(btnTambah))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel2)
                    .addComponent(txtWilayahPenyimpanan, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(btnUpdate))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel3)
                    .addComponent(datePenyimpanan, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(btnHapus))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel4)
                    .addComponent(datePemindahan, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(19, 19, 19)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel5)
                    .addComponent(dateRestok, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(27, 27, 27)
                .addComponent(txtCari, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 190, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(27, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void btnTambahActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnTambahActionPerformed
        try {
            // 1. Validasi Input
            if (txtWilayahPenyimpanan.getText().isEmpty()) {
                JOptionPane.showMessageDialog(null, "Wilayah Penyimpanan tidak boleh kosong");
                txtWilayahPenyimpanan.requestFocus();
            } else {
                // 2. Ambil data dari form dan set ke Variabel di CRUD
                objekKu.VAR_WILAYAH_PENYIMPANAN = txtWilayahPenyimpanan.getText();

                // 3. Konversi JDateChooser ke java.sql.Date (handle null)
                if (datePenyimpanan.getDate() != null) {
                    objekKu.VAR_TANGGAL_PENYIMPANAN = new java.sql.Date(datePenyimpanan.getDate().getTime());
                } else {
                    objekKu.VAR_TANGGAL_PENYIMPANAN = null;
                }

                if (datePemindahan.getDate() != null) {
                    objekKu.VAR_TANGGAL_PEMINDAHAN = new java.sql.Date(datePemindahan.getDate().getTime());
                } else {
                    objekKu.VAR_TANGGAL_PEMINDAHAN = null;
                }

                if (dateRestok.getDate() != null) {
                    objekKu.VAR_TANGGAL_RESTOK = new java.sql.Date(dateRestok.getDate().getTime());
                } else {
                    objekKu.VAR_TANGGAL_RESTOK = null;
                }

                // 4. Panggil metode tambahData() dari CRUD
                objekKu.tambahData();
                
                // 5. Segarkan
                segarkanTabel();
                kosongkanForm();
            }
        } catch (Exception e) {
            JOptionPane.showMessageDialog(null, "Gagal menambah data: " + e.getMessage());
        }
    }//GEN-LAST:event_btnTambahActionPerformed

    private void btnUpdateActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnUpdateActionPerformed
        try {
            // 1. Validasi Input
            if (txtIdWilayah.getText().isEmpty()) {
                JOptionPane.showMessageDialog(null, "Pilih data dari tabel terlebih dahulu");
            } else if (txtWilayahPenyimpanan.getText().isEmpty()) {
                JOptionPane.showMessageDialog(null, "Wilayah Penyimpanan tidak boleh kosong");
                txtWilayahPenyimpanan.requestFocus();
            } else {
                // 2. Ambil data dari form dan set ke Variabel di CRUD
                objekKu.VAR_WILAYAH_PENYIMPANAN = txtWilayahPenyimpanan.getText();

                // 3. Konversi JDateChooser ke java.sql.Date (handle null)
                if (datePenyimpanan.getDate() != null) {
                    objekKu.VAR_TANGGAL_PENYIMPANAN = new java.sql.Date(datePenyimpanan.getDate().getTime());
                } else {
                    objekKu.VAR_TANGGAL_PENYIMPANAN = null;
                }

                if (datePemindahan.getDate() != null) {
                    objekKu.VAR_TANGGAL_PEMINDAHAN = new java.sql.Date(datePemindahan.getDate().getTime());
                } else {
                    objekKu.VAR_TANGGAL_PEMINDAHAN = null;
                }

                if (dateRestok.getDate() != null) {
                    objekKu.VAR_TANGGAL_RESTOK = new java.sql.Date(dateRestok.getDate().getTime());
                } else {
                    objekKu.VAR_TANGGAL_RESTOK = null;
                }

                // 4. Panggil metode updateData() dari CRUD
                objekKu.updateData(txtIdWilayah.getText());
                
                // 5. Segarkan
                segarkanTabel();
                kosongkanForm();
            }
        } catch (Exception e) {
            JOptionPane.showMessageDialog(null, "Gagal mengubah data: " + e.getMessage());
        }
    }//GEN-LAST:event_btnUpdateActionPerformed

    private void btnHapusActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnHapusActionPerformed
        try {
            if (txtIdWilayah.getText().isEmpty()) {
                JOptionPane.showMessageDialog(null, "Pilih data dari tabel terlebih dahulu");
            } else {
                int A = JOptionPane.showConfirmDialog(null, "Yakin ingin menghapus data?", "Konfirmasi", JOptionPane.YES_NO_OPTION);
                if (A == 0) { // 0 = Yes
                    // Panggil metode hapusData() dari CRUD
                    objekKu.hapusData(txtIdWilayah.getText());
                    segarkanTabel();
                    kosongkanForm();
                }
            }
        } catch (Exception e) {
            JOptionPane.showMessageDialog(null, "Gagal menghapus data: " + e.getMessage());
        }
    }//GEN-LAST:event_btnHapusActionPerformed

    private void tableWilayahMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_tableWilayahMouseClicked
        try {
            int baris = tableWilayah.rowAtPoint(evt.getPoint());

            // Ambil data dari tabel
            // Indeks: 0=ID, 1=Wilayah, 2=TglPenyimpanan, 3=TglPemindahan, 4=TglRestok
            String id = tableWilayah.getValueAt(baris, 0).toString();
            String wilayah = tableWilayah.getValueAt(baris, 1).toString();
            
            // Ambil object Date (bisa jadi null)
            Object tglSimpanObj = tableWilayah.getValueAt(baris, 2);
            Object tglPindahObj = tableWilayah.getValueAt(baris, 3);
            Object tglRestokObj = tableWilayah.getValueAt(baris, 4);

            // Set data ke Form
            txtIdWilayah.setText(id);
            txtWilayahPenyimpanan.setText(wilayah);

            // Set JDateChooser (handle null)
            if (tglSimpanObj != null) {
                datePenyimpanan.setDate((java.util.Date) tglSimpanObj);
            } else {
                datePenyimpanan.setDate(null);
            }
            
            if (tglPindahObj != null) {
                datePemindahan.setDate((java.util.Date) tglPindahObj);
            } else {
                datePemindahan.setDate(null);
            }
            
            if (tglRestokObj != null) {
                dateRestok.setDate((java.util.Date) tglRestokObj);
            } else {
                dateRestok.setDate(null);
            }

        } catch (Exception e) {
            JOptionPane.showMessageDialog(null, "Error memilih data: " + e.getMessage());
        }
    }//GEN-LAST:event_tableWilayahMouseClicked

    private void txtCariKeyPressed(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_txtCariKeyPressed
        // Fungsi pencarian (live search), sama seperti frame_jadwal_sidang
        // Ini memanggil metode tampilDataWilayah dengan SQL yang dimodifikasi
        String cari = txtCari.getText();
        String sql = "SELECT * FROM wilayah WHERE Wilayah_Penyimpanan LIKE '%" + cari + "%'";
        objekKu.tampilDataWilayah(tableWilayah, sql);
    }//GEN-LAST:event_txtCariKeyPressed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(frame_wilayah.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(frame_wilayah.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(frame_wilayah.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(frame_wilayah.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new frame_wilayah().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnHapus;
    private javax.swing.JButton btnTambah;
    private javax.swing.JButton btnUpdate;
    private com.toedter.calendar.JDateChooser datePemindahan;
    private com.toedter.calendar.JDateChooser datePenyimpanan;
    private com.toedter.calendar.JDateChooser dateRestok;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTable tableWilayah;
    private javax.swing.JTextField txtCari;
    private javax.swing.JTextField txtIdWilayah;
    private javax.swing.JTextField txtWilayahPenyimpanan;
    // End of variables declaration//GEN-END:variables
}