/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package frame;

import configDB.crud_ketersediaan_alat;
import java.sql.Date; // Penting untuk konversi JDateChooser
import java.util.ArrayList; // Penting untuk ComboBox
import javax.swing.JOptionPane;

/**
 *
 * @author User
 */
public class frame_ketersediaan_alat extends javax.swing.JFrame {

    private crud_ketersediaan_alat objekKu;

    /**
     * Creates new form frame_ketersediaan_alat
     */
    public frame_ketersediaan_alat() {
        initComponents();
        this.setLocationRelativeTo(null);
        objekKu = new crud_ketersediaan_alat();
        txtIdStatus.setEnabled(false); // ID Status di-set oleh database (AI)
        muatComboBoxIdAlat(); // Panggil metode untuk isi ComboBox
        segarkanTabel(); // Tampilkan data saat frame dibuka
    }

    // Metode untuk memuat ID Alat ke ComboBox
    private void muatComboBoxIdAlat() {
        try {
            cmbIdAlat.removeAllItems(); // Kosongkan dulu
            ArrayList<String> listIdAlat = objekKu.getIDAlat(); // Ambil data dari CRUD
            for (String id : listIdAlat) {
                cmbIdAlat.addItem(id);
            }
        } catch (Exception e) {
            JOptionPane.showMessageDialog(null, "Gagal memuat ID Alat: " + e.getMessage());
        }
    }

    // Metode untuk menyegarkan data tabel
    private void segarkanTabel() {
        objekKu.tampilDataKetersediaan(tableKetersediaanAlat);
    }
    
    // Metode untuk mengosongkan form
    private void kosongkanForm() {
        txtIdStatus.setText(null);
        cmbIdAlat.setSelectedIndex(0); // Kembali ke item pertama
        txtStatus.setText(null);
        datePenempatan.setDate(null); // Kosongkan JDateChooser
        dateSelesai.setDate(null); // Kosongkan JDateChooser
    }


    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        txtIdStatus = new javax.swing.JTextField();
        txtStatus = new javax.swing.JTextField();
        cmbIdAlat = new javax.swing.JComboBox<>();
        datePenempatan = new com.toedter.calendar.JDateChooser();
        dateSelesai = new com.toedter.calendar.JDateChooser();
        btnTambah = new javax.swing.JButton();
        btnUpdate = new javax.swing.JButton();
        btnHapus = new javax.swing.JButton();
        txtCari = new javax.swing.JTextField();
        jScrollPane1 = new javax.swing.JScrollPane();
        tableKetersediaanAlat = new javax.swing.JTable();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);
        setTitle("Kelola Ketersediaan Alat");

        jLabel1.setText("ID Status");

        jLabel2.setText("ID Alat");

        jLabel3.setText("Status");

        jLabel4.setText("Tanggal Penempatan");

        jLabel5.setText("Tanggal Selesai");

        cmbIdAlat.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Item 1", "Item 2", "Item 3", "Item 4" }));

        datePenempatan.setDateFormatString("yyyy-MM-dd");

        dateSelesai.setDateFormatString("yyyy-MM-dd");

        btnTambah.setText("Tambah");
        btnTambah.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnTambahActionPerformed(evt);
            }
        });

        btnUpdate.setText("Update");
        btnUpdate.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnUpdateActionPerformed(evt);
            }
        });

        btnHapus.setText("Hapus");
        btnHapus.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnHapusActionPerformed(evt);
            }
        });

        txtCari.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyPressed(java.awt.event.KeyEvent evt) {
                txtCariKeyPressed(evt);
            }
        });

        tableKetersediaanAlat.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null, null, null},
                {null, null, null, null, null, null},
                {null, null, null, null, null, null},
                {null, null, null, null, null, null}
            },
            new String [] {
                "Title 1", "Title 2", "Title 3", "Title 4", "Title 5", "Title 6"
            }
        ));
        tableKetersediaanAlat.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                tableKetersediaanAlatMouseClicked(evt);
            }
        });
        jScrollPane1.setViewportView(tableKetersediaanAlat);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(28, 28, 28)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(jScrollPane1, javax.swing.GroupLayout.DEFAULT_SIZE, 469, Short.MAX_VALUE)
                    .addComponent(txtCari)
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel1)
                            .addComponent(jLabel2)
                            .addComponent(jLabel3)
                            .addComponent(jLabel4)
                            .addComponent(jLabel5))
                        .addGap(25, 25, 25)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(txtIdStatus)
                            .addComponent(txtStatus)
                            .addComponent(cmbIdAlat, 0, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(datePenempatan, javax.swing.GroupLayout.DEFAULT_SIZE, 160, Short.MAX_VALUE)
                            .addComponent(dateSelesai, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                        .addGap(41, 41, 41)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(btnTambah, javax.swing.GroupLayout.DEFAULT_SIZE, 130, Short.MAX_VALUE)
                            .addComponent(btnUpdate, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(btnHapus, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))))
                .addContainerGap(28, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(25, 25, 25)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel1)
                    .addComponent(txtIdStatus, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(btnTambah))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel2)
                    .addComponent(cmbIdAlat, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(btnUpdate))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel3)
                    .addComponent(txtStatus, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(btnHapus))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel4)
                    .addComponent(datePenempatan, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(19, 19, 19)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel5)
                    .addComponent(dateSelesai, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(28, 28, 28)
                .addComponent(txtCari, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 200, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(22, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void btnTambahActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnTambahActionPerformed
        try {
            // 1. Validasi Input
            if (txtStatus.getText().isEmpty()) {
                JOptionPane.showMessageDialog(null, "Status tidak boleh kosong");
                txtStatus.requestFocus();
            } else if (datePenempatan.getDate() == null) {
                JOptionPane.showMessageDialog(null, "Tanggal Penempatan tidak boleh kosong");
                datePenempatan.requestFocus();
            } else {
                // 2. Ambil data dari form dan set ke Variabel di CRUD
                objekKu.VAR_ID_ALAT = Integer.parseInt(cmbIdAlat.getSelectedItem().toString());
                objekKu.VAR_STATUS = txtStatus.getText();
                
                // Konversi java.util.Date (JDateChooser) ke java.sql.Date (Database)
                objekKu.VAR_TANGGAL_PENEMPATAN = new java.sql.Date(datePenempatan.getDate().getTime());
                
                // Handle Tanggal Selesai (boleh null)
                if (dateSelesai.getDate() != null) {
                    objekKu.VAR_TANGGAL_SELESAI = new java.sql.Date(dateSelesai.getDate().getTime());
                } else {
                    objekKu.VAR_TANGGAL_SELESAI = null;
                }

                // 3. Panggil metode tambahData() dari CRUD
                objekKu.tambahData();
                
                // 4. Segarkan tabel
                segarkanTabel();
                kosongkanForm();
            }
        } catch (Exception e) {
            JOptionPane.showMessageDialog(null, "Gagal menambah data: " + e.getMessage());
        }
    }//GEN-LAST:event_btnTambahActionPerformed

    private void btnUpdateActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnUpdateActionPerformed
        try {
            // 1. Validasi Input
            if (txtIdStatus.getText().isEmpty()) {
                JOptionPane.showMessageDialog(null, "Pilih data dari tabel terlebih dahulu");
            } else if (txtStatus.getText().isEmpty()) {
                JOptionPane.showMessageDialog(null, "Status tidak boleh kosong");
                txtStatus.requestFocus();
            } else if (datePenempatan.getDate() == null) {
                JOptionPane.showMessageDialog(null, "Tanggal Penempatan tidak boleh kosong");
                datePenempatan.requestFocus();
            } else {
                // 2. Ambil data dari form dan set ke Variabel di CRUD
                objekKu.VAR_ID_ALAT = Integer.parseInt(cmbIdAlat.getSelectedItem().toString());
                objekKu.VAR_STATUS = txtStatus.getText();
                objekKu.VAR_TANGGAL_PENEMPATAN = new java.sql.Date(datePenempatan.getDate().getTime());
                
                if (dateSelesai.getDate() != null) {
                    objekKu.VAR_TANGGAL_SELESAI = new java.sql.Date(dateSelesai.getDate().getTime());
                } else {
                    objekKu.VAR_TANGGAL_SELESAI = null;
                }

                // 3. Panggil metode updateData() dari CRUD
                objekKu.updateData(txtIdStatus.getText());
                
                // 4. Segarkan tabel
                segarkanTabel();
                kosongkanForm();
            }
        } catch (Exception e) {
            JOptionPane.showMessageDialog(null, "Gagal mengubah data: " + e.getMessage());
        }
    }//GEN-LAST:event_btnUpdateActionPerformed

    private void btnHapusActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnHapusActionPerformed
        try {
            if (txtIdStatus.getText().isEmpty()) {
                JOptionPane.showMessageDialog(null, "Pilih data dari tabel terlebih dahulu");
            } else {
                int A = JOptionPane.showConfirmDialog(null, "Yakin ingin menghapus data?", "Konfirmasi", JOptionPane.YES_NO_OPTION);
                if (A == 0) { // 0 = Yes
                    // Panggil metode hapusData() dari CRUD
                    objekKu.hapusData(txtIdStatus.getText());
                    segarkanTabel();
                    kosongkanForm();
                }
            }
        } catch (Exception e) {
            JOptionPane.showMessageDialog(null, "Gagal menghapus data: " + e.getMessage());
        }
    }//GEN-LAST:event_btnHapusActionPerformed

    private void tableKetersediaanAlatMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_tableKetersediaanAlatMouseClicked
        try {
            int baris = tableKetersediaanAlat.rowAtPoint(evt.getPoint());

            // Ambil data dari tabel (Indeks kolom sesuai query JOIN di CRUD)
            // 0: ID_Status, 1: ID_Alat, 2: Nama_Alat, 3: Status, 4: Tgl_Penempatan, 5: Tgl_Selesai
            String idStatus = tableKetersediaanAlat.getValueAt(baris, 0).toString();
            String idAlat = tableKetersediaanAlat.getValueAt(baris, 1).toString();
            String status = tableKetersediaanAlat.getValueAt(baris, 3).toString();
            
            // Ambil object Date (bisa jadi null)
            Object tglPenempatanObj = tableKetersediaanAlat.getValueAt(baris, 4);
            Object tglSelesaiObj = tableKetersediaanAlat.getValueAt(baris, 5);

            // Set data ke Form
            txtIdStatus.setText(idStatus);
            cmbIdAlat.setSelectedItem(idAlat); // Set ComboBox berdasarkan ID
            txtStatus.setText(status);

            // Set JDateChooser (handle null)
            if (tglPenempatanObj != null) {
                datePenempatan.setDate((java.util.Date) tglPenempatanObj);
            } else {
                datePenempatan.setDate(null);
            }
            
            if (tglSelesaiObj != null) {
                dateSelesai.setDate((java.util.Date) tglSelesaiObj);
            } else {
                dateSelesai.setDate(null);
            }

        } catch (Exception e) {
            JOptionPane.showMessageDialog(null, "Error memilih data: " + e.getMessage());
        }
    }//GEN-LAST:event_tableKetersediaanAlatMouseClicked

    private void txtCariKeyPressed(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_txtCariKeyPressed
        // Panggil metode cariData (yang baru Anda tambahkan ke CRUD)
        String kriteria = txtCari.getText();
        if (kriteria.isEmpty()) {
            segarkanTabel(); // Jika search kosong, tampilkan semua
        } else {
            objekKu.cariData(tableKetersediaanAlat, kriteria);
        }
    }//GEN-LAST:event_txtCariKeyPressed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(frame_ketersediaan_alat.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(frame_ketersediaan_alat.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(frame_ketersediaan_alat.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(frame_ketersediaan_alat.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new frame_ketersediaan_alat().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnHapus;
    private javax.swing.JButton btnTambah;
    private javax.swing.JButton btnUpdate;
    private javax.swing.JComboBox<String> cmbIdAlat;
    private com.toedter.calendar.JDateChooser datePenempatan;
    private com.toedter.calendar.JDateChooser dateSelesai;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTable tableKetersediaanAlat;
    private javax.swing.JTextField txtCari;
    private javax.swing.JTextField txtIdStatus;
    private javax.swing.JTextField txtStatus;
    // End of variables declaration//GEN-END:variables
}